const RECIPES_DATA = [
    // SUHOOR (50)
    { category: 'breakfast', name_en: "Ful Medames", name_ar: "فول مدمس", desc_en: "Slow-cooked fava beans with olive oil and cumin.", desc_ar: "فول مدمس مطهو ببطء بالزيت والكمون." },
    { category: 'breakfast', name_en: "Shakshuka", name_ar: "شكشوكة", desc_en: "Poached eggs in tomato and bell pepper sauce.", desc_ar: "بيض مسلوق في صلصة الطماطم والفلفل." },
    { category: 'breakfast', name_en: "Labneh with Za'atar", name_ar: "لبنة بالزعتر", desc_en: "Creamy yogurt cheese topped with olive oil and za'atar.", desc_ar: "لبنة كريمية بزيت الزيتون والزعتر الأصلي." },
    { category: 'breakfast', name_en: "Date & Peanut Butter Oats", name_ar: "شوفان بالتمر والفول السوداني", desc_en: "Overnight oats with chopped dates for energy.", desc_ar: "شوفان مشبع مع التمر وزبدة الفول السوداني." },
    { category: 'breakfast', name_en: "Honey Greek Yogurt", name_ar: "زبادي يوناني بالعسل", desc_en: "Thick yogurt with honey and walnuts.", desc_ar: "زبادي سميك مع العسل والجوز المقرمش." },
    { category: 'breakfast', name_en: "Boiled Eggs & Avocado", name_ar: "بيض مسلوق وأفوكادو", desc_en: "Simple protein-rich breakfast with sliced avocado.", desc_ar: "وجبة بروتين بسيطة مع شرائح الأفوكادو." },
    { category: 'breakfast', name_en: "Cheese Manakish", name_ar: "مناقيش جبنة", desc_en: "Warm flatbread topped with melted Akkawi cheese.", desc_ar: "خبز دافئ مغطى بجبنة العكاوي الذائبة." },
    { category: 'breakfast', name_en: "Fruit & Nut Parfait", name_ar: "بارفيه الفواكه والمكسرات", desc_en: "Layers of fruit, yogurt, and granola.", desc_ar: "طبقات من الفواكه والزبادي والجرانولا." },
    { category: 'breakfast', name_en: "Tabbouleh Toast", name_ar: "توست التبولة", desc_en: "Whole grain toast topped with fresh parsley salad.", desc_ar: "خبز القمح المحمص مع سلطة التبولة الطازجة." },
    { category: 'breakfast', name_en: "Banana & Almond Smoothie", name_ar: "سموثي الموز واللوز", desc_en: "Smoothie with milk, banana, and almond butter.", desc_ar: "مشروب مغذي بالحليب والموز وزبدة اللوز." },
    { category: 'breakfast', name_en: "Classic Hummus Toast", name_ar: "توست الحمص الكلاسيكي", desc_en: "Hummus spread on rye bread with cucumber slices.", desc_ar: "حمص على خبز الراي مع شرائح الخيار." },
    { category: 'breakfast', name_en: "Egg White Omelet", name_ar: "أومليت بياض البيض", desc_en: "Light omelet with spinach and mushrooms.", desc_ar: "أومليت خفيف مع السبانخ والمشروم." },
    { category: 'breakfast', name_en: "Falafel Wrap", name_ar: "لفافة فلافل", desc_en: "Baked falafel in whole wheat wrap with tahini.", desc_ar: "فلافل مشوية في خبز القمح الكامل مع الطحينة." },
    { category: 'breakfast', name_en: "Quinoa Breakfast Bowl", name_ar: "وعاء الكينوا للفطور", desc_en: "Quinoa with almond milk, cinnamon, and berries.", desc_ar: "كينوا بحليب اللوز والقرفة والتوت." },
    { category: 'breakfast', name_en: "Smoked Turkey Sandwich", name_ar: "ساندويتش تركي مدخن", desc_en: "Turkey slices with lettuce and low-fat cheese.", desc_ar: "شرائح الحبش مع الخس والجبنة قليلة الدسم." },
    { category: 'breakfast', name_en: "Chia Seed Pudding", name_ar: "بودينج بذور الشيا", desc_en: "Chia seeds soaked in coconut milk with mango.", desc_ar: "بذور الشيا بحليب جوز الهند والمانجو." },
    { category: 'breakfast', name_en: "Lentil Soup", name_ar: "شوربة عدس", desc_en: "Warm yellow lentil soup with lemon.", desc_ar: "شوربة عدس أصفر دافئة مع الليمون." },
    { category: 'breakfast', name_en: "Cottage Cheese & Peaches", name_ar: "جبنة قريش بالخوخ", desc_en: "High protein cheese with sliced peaches.", desc_ar: "جبنة قريش غنية بالبروتين مع شرائح الخوخ." },
    { category: 'breakfast', name_en: "Peanut Butter Banana Wrap", name_ar: "لفافة موز وزبدة الفول سوداني", desc_en: "Whole wheat tortilla with peanut butter and banana.", desc_ar: "خبز تورتيلا مع زبدة الفول سوداني وموز." },
    { category: 'breakfast', name_en: "Mashed Sweet Potato", name_ar: "بطاطا حلوة مهروسة", desc_en: "Roasted sweet potato topped with pecans.", desc_ar: "بطاطا حلوة مشوية مع جوز البقان." },
    { category: 'breakfast', name_en: "Turkey & Egg Muffins", name_ar: "مافن البيض بالتركي", desc_en: "Baked egg cups with turkey and peppers.", desc_ar: "أكواب البيض المخبوزة مع الحبش والفلفل." },
    { category: 'breakfast', name_en: "Honey Ginger Tea & Crackers", name_ar: "شاي زنجبيل ورقائق", desc_en: "Soothing tea with whole grain crackers.", desc_ar: "شاي مهدئ مع رقائق الحبوب الكاملة." },
    { category: 'breakfast', name_en: "Arabic Omelet (Ejjeh)", name_ar: "عجة بيض عربية", desc_en: "Egg pancake with fresh herbs and onions.", desc_ar: "فطيرة بيض بالأعشاب الطازجة والبصل." },
    { category: 'breakfast', name_en: "Buckwheat Pancakes", name_ar: "بانكيك الحنطة السوداء", desc_en: "Healthy pancakes served with maple syrup.", desc_ar: "بانكيك صحي يقدم مع شراب القيقب." },
    { category: 'breakfast', name_en: "Grilled Halloumi", name_ar: "حلوم مشوي", desc_en: "Grilled halloumi cheese with tomato slices.", desc_ar: "جبنة حلوم مشوية مع شرائح الطماطم." },
    { category: 'breakfast', name_en: "Tahini & Molasses Toast", name_ar: "توست الطحينة والدبس", desc_en: "Traditional Middle Eastern energy mix on toast.", desc_ar: "خليط الطاقة التقليدي من الطحينة والدبس." },
    { category: 'breakfast', name_en: "Spinach Fatayer", name_ar: "فطاير سبانخ", desc_en: "Triangular pastries filled with lemony spinach.", desc_ar: "معجنات مثلثية محشوة بالسبانخ والليمون." },
    { category: 'breakfast', name_en: "Oatmeal Cookies", name_ar: "كوكيز الشوفان", desc_en: "Healthy cookies with oats, honey, and raisins.", desc_ar: "بسكويت صحي بالشوفان والعسل والزبيب." },
    { category: 'breakfast', name_en: "Baked Apple with Cinnamon", name_ar: "تفاح مشوي بالقرفة", desc_en: "Warm apple slices with a hint of honey.", desc_ar: "شرائح تفاح دافئة مع القليل من العسل." },
    { category: 'breakfast', name_en: "Feta & Watermelon", name_ar: "جبنة فيتا وبطيخ", desc_en: "Refreshing mix of salty cheese and sweet fruit.", desc_ar: "مزيج منعش من الجبنة المالحة والفاكهة الحلوة." },
    { category: 'breakfast', name_en: "Almond Flour Pancakes", name_ar: "بانكيك دقيق اللوز", desc_en: "Keto-friendly pancakes with berries.", desc_ar: "بانكيك كيتو بدقيق اللوز والتوت." },
    { category: 'breakfast', name_en: "Lentil Salad", name_ar: "سلطة عدس", desc_en: "Cold lentil salad with lemon and parsley.", desc_ar: "سلطة عدس باردة بالليمون والبقدونس." },
    { category: 'breakfast', name_en: "Roasted Chickpeas", name_ar: "حمص حمص مقرمش", desc_en: "Spicy roasted chickpeas for a crunchy Suhoor.", desc_ar: "حمص محمص بالتوابل لوجبة سحور مقرمشة." },
    { category: 'breakfast', name_en: "Cucumber & Yogurt Salad", name_ar: "سلطة خيار باللبن", desc_en: "Cooling yogurt with garlic and dried mint.", desc_ar: "زبادي منعش بالثوم والنعناع الجاف." },
    { category: 'breakfast', name_en: "Date Nut Bars", name_ar: "ألواح التمر والمكسرات", desc_en: "Homemade energy bars with dates and almonds.", desc_ar: "ألواح طاقة منزلية بالتمر واللوز." },
    { category: 'breakfast', name_en: "Scrambled Eggs with Kale", name_ar: "بيض بالكرنب الأجعد", desc_en: "Nutritious scrambled eggs with sautéed kale.", desc_ar: "بيض مخفوق مغذي بالكرنب الأجعد." },
    { category: 'breakfast', name_en: "Beef Jerky & Nuts", name_ar: "لحم مجفف ومكسرات", desc_en: "High protein snack for short Suhoor.", desc_ar: "وجبة خفيفة غنية بالبروتين لسحور سريع." },
    { category: 'breakfast', name_en: "Whole Grain Bagel", name_ar: "بيجل حبوب كاملة", desc_en: "Bagel with light cream cheese and sprouts.", desc_ar: "بيجل مع جبنة كريمية خفيفة وبراعم." },
    { category: 'breakfast', name_en: "Pumpkin Seed Granola", name_ar: "جرانولا بذور اليقطين", desc_en: "Crunchy granola served with cold milk.", desc_ar: "جرانولا مقرمشة تقدم مع الحليب البارد." },
    { category: 'breakfast', name_en: "Tuna Salad on Crackers", name_ar: "سلطة تونة على رقائق", desc_en: "Light tuna mix with celery and lemon.", desc_ar: "خليط تونة خفيف مع الكرفس والليمون." },
    { category: 'breakfast', name_en: "Zucchini Fritters", name_ar: "عجة كوسة", desc_en: "Grated zucchini and egg pan-fried patties.", desc_ar: "أقراص الكوسة والبيض المقلية." },
    { category: 'breakfast', name_en: "Peanut Butter Rice Cakes", name_ar: "كعك الأرز بزبدة الفول", desc_en: "Rice cakes with peanut butter and hemp seeds.", desc_ar: "كعك الأرز بزبدة الفول وبذور القنب." },
    { category: 'breakfast', name_en: "Breakfast Burrito", name_ar: "بوريتو الفطور", desc_en: "Eggs, black beans, and salsa in a tortilla.", desc_ar: "بيض وفاصوليا سوداء وصلصة في تورتيلا." },
    { category: 'breakfast', name_en: "Steamed Asparagus & Eggs", name_ar: "بهيجة وهليون", desc_en: "Lightly steamed asparagus with soft boiled eggs.", desc_ar: "هليون مطهو على البخار مع بيض برشت." },
    { category: 'breakfast', name_en: "Cinnamon Raisin Toast", name_ar: "توست القرفة والزبيب", desc_en: "Sweet toasted bread with a layer of butter.", desc_ar: "خبز محمص حلو مع طبقة من الزبدة." },
    { category: 'breakfast', name_en: "Labneh & Cucumber Sandwich", name_ar: "ساندويتش لبنة وخيار", desc_en: "Classic cooling sandwich with olive oil.", desc_ar: "ساندويتش كلاسيكي منعش بزيت الزيتون." },
    { category: 'breakfast', name_en: "Blueberry Smoothie Bowl", name_ar: "وعاء سموثي التوت", desc_en: "Thick blueberry smoothie topped with nuts.", desc_ar: "سموثي توت كثيف مغطى بالمكسرات." },
    { category: 'breakfast', name_en: "Hard Boiled Egg & Tea", name_ar: "بيض شاي", desc_en: "The simplest traditional Suhoor.", desc_ar: "أبسط سحور تقليدي: بيض مسلوق وشاي." },
    { category: 'breakfast', name_en: "Hummus & Carrot Sticks", name_ar: "حمص وجزر", desc_en: "Crunchy carrots with creamy hummus dip.", desc_ar: "جزر مقرمش مع تغميسة الحمص الكريمية." },
    { category: 'breakfast', name_en: "Walnut & Date Shake", name_ar: "مخفوق الجوز والتمر", desc_en: "Energy-packed shake with milk and honey.", desc_ar: "مخفوق مليء بالطاقة بالحليب والعسل." },

    // IFTAR (50)
    { category: 'lunch', name_en: "Lamb Mansaf", name_ar: "منسف لحم", desc_en: "Jordon's national dish with jameed and rice.", desc_ar: "طبق الأردن الوطني بالجميد والأرز." },
    { category: 'lunch', name_en: "Chicken Maqluba", name_ar: "مقلوبة دجاج", desc_en: "Upside-down rice with chicken and eggplant.", desc_ar: "أرز مقلوب مع الدجاج والباذنجان." },
    { category: 'lunch', name_en: "Kabsa", name_ar: "كبسة سعودية", desc_en: "Spiced rice with slow-cooked meat and nuts.", desc_ar: "أرز متبل مع لحم مطهو ببطء ومكسرات." },
    { category: 'lunch', name_en: "Egyptian Koshary", name_ar: "كشري مصري", desc_en: "Rice, pasta, and lentils with tomato sauce.", desc_ar: "أرز ومكرونة وعدس مع صلصة طماطم." },
    { category: 'lunch', name_en: "Lamb Ouzi", name_ar: "أوزي لحم", desc_en: "Rice with peas, carrots, and roasted lamb.", desc_ar: "أرز بالبسلة والجزر مع لحم مشوي." },
    { category: 'lunch', name_en: "Stuffed Vine Leaves", name_ar: "ورق عنب محشي", desc_en: "Vine leaves stuffed with rice and herbs.", desc_ar: "ورق عنب محشو بالأرز والأعشاب." },
    { category: 'lunch', name_en: "Beef Bamia (Okra)", name_ar: "بامية باللحم", desc_en: "Beef and okra stew in tomato garlic sauce.", desc_ar: "يخنة لحم وبامية بصلصة الطماطم والثوم." },
    { category: 'lunch', name_en: "Chicken Musakhan", name_ar: "مسخن دجاج", desc_en: "Palestinian chicken with sumac and onions.", desc_ar: "دجاج فلسطيني بالسماق والبصل." },
    { category: 'lunch', name_en: "Lamb Mandi", name_ar: "مندي لحم", desc_en: "Meat cooked in a pit with smoky rice.", desc_ar: "لحم مطهو في حفرة مع أرز مدخن." },
    { category: 'lunch', name_en: "Sayadieh Fish", name_ar: "صيادية سمك", desc_en: "Spiced fish served with brown onion rice.", desc_ar: "سمك متبل يقدم مع أرز البصل البني." },
    { category: 'lunch', name_en: "Beef Kofta Nayeh", name_ar: "كفتة بالصينية", desc_en: "Baked beef kebabs with potatoes and tahini.", desc_ar: "كباب لحم مخبوز مع البطاطس والطحينة." },
    { category: 'lunch', name_en: "Chicken Freekeh", name_ar: "فريكة بالدجاج", desc_en: "Roasted green wheat with spicy chicken.", desc_ar: "قمح أخضر محمص مع دجاج متبل." },
    { category: 'lunch', name_en: "Lamb Tagine", name_ar: "طاجين لحم", desc_en: "Moroccan stew with prunes and apricots.", desc_ar: "يخنة مغربية بالقراصيا والمشمش." },
    { category: 'lunch', name_en: "Chicken Shish Tawook", name_ar: "شيش طاووق", desc_en: "Marinated chicken skewers with garlic paste.", desc_ar: "أسياخ دجاج متبلة مع كريم الثوم." },
    { category: 'lunch', name_en: "Roasted Lamb Leg", name_ar: "فخذ خروف مشوي", desc_en: "Slow roasted lamb with rosemary and garlic.", desc_ar: "فخذ خروف مشوي ببطء بالروزماري والثوم." },
    { category: 'lunch', name_en: "Beef Mulukhiyah", name_ar: "ملوخية باللحم", desc_en: "Jute mallow soup with tender beef chunks.", desc_ar: "شوربة الملوخية مع قطع اللحم الطرية." },
    { category: 'lunch', name_en: "Chicken Biryani", name_ar: "برياني دجاج", desc_en: "Fragrant rice layered with spiced chicken.", desc_ar: "أرز عطري طبقات مع دجاج متبل." },
    { category: 'lunch', name_en: "Lamb Chops", name_ar: "ريش غنم", desc_en: "Grilled lamb chops with lemon and herbs.", desc_ar: "ريش غنم مشوية بالليمون والأعشاب." },
    { category: 'lunch', name_en: "Kousa Mahshi", name_ar: "كوسا محشي", desc_en: "Zucchini stuffed with rice and minced meat.", desc_ar: "كوسا محشوة بالأرز واللحم المفروم." },
    { category: 'lunch', name_en: "Dawood Basha", name_ar: "داوود باشا", desc_en: "Meatballs in hot tomato sauce with pine nuts.", desc_ar: "كرات لحم بصلصة طماطم ساخنة وصنوبر." },
    { category: 'lunch', name_en: "Grilled Sea Bass", name_ar: "سيباس مشوي", desc_en: "Whole fish grilled with Mediterranean spices.", desc_ar: "سمك كامل مشوي ببهارات البحر المتوسط." },
    { category: 'lunch', name_en: "Beef Shawarma Plate", name_ar: "صحن شاورما لحم", desc_en: "Beef shawarma with tahini and parsley.", desc_ar: "شاورما لحم مع طحينة وبقدونس." },
    { category: 'lunch', name_en: "Chicken Kabab", name_ar: "كباب دجاج", desc_en: "Grilled minced chicken with onions and herbs.", desc_ar: "دجاج مفروم مشوي مع البصل والأعشاب." },
    { category: 'lunch', name_en: "Maglooba with Cauliflower", name_ar: "مقلوبة زهرة", desc_en: "Rice with fried cauliflower and meat.", desc_ar: "أرز مع الزهرة المقلية واللحم." },
    { category: 'lunch', name_en: "Kebab Karaz", name_ar: "كباب كرز", desc_en: "Aleppo meatballs in cherry sauce.", desc_ar: "كرات لحم حلبية بصلصة الكرز." },
    { category: 'lunch', name_en: "Moussaka", name_ar: "مسقعة", desc_en: "Baked eggplant with beef and béchamel sauce.", desc_ar: "باذنجان مخبوز باللحم وصلصة البشاميل." },
    { category: 'lunch', name_en: "Shrimp Machboos", name_ar: "مجبوس ربيان", desc_en: "Gulf style rice with spiced shrimp.", desc_ar: "أرز على الطريقة الخليجية بالربيان." },
    { category: 'lunch', name_en: "Beef Stew with Peas", name_ar: "يخنة بسلة ولحم", desc_en: "Classic family comfort food stew.", desc_ar: "يخنة بازلاء ولحم كلاسيكية." },
    { category: 'lunch', name_en: "Chicken Adobo", name_ar: "دجاج أدوبو", desc_en: "Tangy chicken stew with soy and vinegar.", desc_ar: "يخنة دجاج حامضة بالصويا والخل." },
    { category: 'lunch', name_en: "Lamb Haneeth", name_ar: "حنيذ لحم", desc_en: "Yemeni slow-roasted spiced lamb.", desc_ar: "لحم حنيذ يمني مشوي متبل." },
    { category: 'lunch', name_en: "Mujadara", name_ar: "مجدرة", desc_en: "Lentils and rice topped with fried onions.", desc_ar: "عدس وأرز مغطى بالبصل المقلي." },
    { category: 'lunch', name_en: "Sheikh al-Mahshi", name_ar: "شيخ المحشي", desc_en: "Eggplant or zucchini stuffed with meat in yogurt.", desc_ar: "باذنجان أو كوسا باللحم واللبن." },
    { category: 'lunch', name_en: "Grilled Salmon", name_ar: "سلمون مشوي", desc_en: "Salmon fillet with a lemon butter glaze.", desc_ar: "فيليه سلمون بصلصة الليمون والزبدة." },
    { category: 'lunch', name_en: "Beef Lasagna", name_ar: "لازانيا لحم", desc_en: "Layered pasta with meat and cheese.", desc_ar: "مكرونة طبقات مع اللحم والجبن." },
    { category: 'lunch', name_en: "Chicken Alfredo", name_ar: "دجاج ألفريدو", desc_en: "Creamy pasta with grilled chicken slices.", desc_ar: "مكرونة كريمية مع شرائح دجاج مشوي." },
    { category: 'lunch', name_en: "Lamb Fattah", name_ar: "فتة لحم", desc_en: "Rice, bread, and meat with garlic vinegar sauce.", desc_ar: "أرز وخبز ولحم بصلصة الثوم والخل." },
    { category: 'lunch', name_en: "Vegetable Couscous", name_ar: "كسكسي بالخضار", desc_en: "Steamed semolina with seven vegetables.", desc_ar: "سميد مطهو على البخار مع سبع خضروات." },
    { category: 'lunch', name_en: "Beef Stroganoff", name_ar: "بيف ستروجانوف", desc_en: "Beef strips in a creamy mushroom sauce.", desc_ar: "شرائح لحم بصلصة المشروم الكريمية." },
    { category: 'lunch', name_en: "Chicken Jalfrezi", name_ar: "دجاج جالفريزي", desc_en: "Spicy stir-fried chicken with peppers.", desc_ar: "دجاج مقلي حار مع الفلفل." },
    { category: 'lunch', name_en: "Butter Chicken", name_ar: "دجاج بالزبدة", desc_en: "Tender chicken in a mild creamy tomato gravy.", desc_ar: "دجاج طري في صلصة طماطم كريمية." },
    { category: 'lunch', name_en: "Lamb Kabsa", name_ar: "كبسة لحم", desc_en: "Richly spiced rice with lamb chunks.", desc_ar: "أرز غني بالتوابل مع قطع اللحم." },
    { category: 'lunch', name_en: "Eggplant Fatteh", name_ar: "فتة باذنجان", desc_en: "Layers of eggplant, bread, and yogurt sauce.", desc_ar: "طبقات باذنجان وخبز وصلصة زبادي." },
    { category: 'lunch', name_en: "Meat Pie", name_ar: "فطيرة لحم", desc_en: "Savory puff pastry filled with minced meat.", desc_ar: "عجينة مقرمشة محشوة باللحم المفروم." },
    { category: 'lunch', name_en: "Stuffed Peppers", name_ar: "فلفل محشي", desc_en: "Bell peppers filled with spiced rice and beef.", desc_ar: "فلفل رومي محشو بالأرز واللحم." },
    { category: 'lunch', name_en: "Baked Potato with Meat", name_ar: "بطاطس محشوة", desc_en: "Large potato shells filled with spicy beef.", desc_ar: "بطاطس محشوة باللحم المتبل." },
    { category: 'lunch', name_en: "Chicken Schnitzel", name_ar: "شنسل دجاج", desc_en: "Breaded and fried chicken breast.", desc_ar: "صدور دجاج مغطاة بالبقسماط ومقلية." },
    { category: 'lunch', name_en: "Lamb Quzi Bowl", name_ar: "صحن قوزي", desc_en: "Roast lamb over cardamom rice.", desc_ar: "لحم مشوي فوق أرز بالهيل." },
    { category: 'lunch', name_en: "Beef Curry", name_ar: "كاري لحم", desc_en: "Spicy curry stew with potatoes and peas.", desc_ar: "يخنة كاري حارة مع البطاطس والبسلة." },
    { category: 'lunch', name_en: "Grilled Calamari", name_ar: "كلماري مشوي", desc_en: "Calamari tubes with lemon and garlic butter.", desc_ar: "كلماري مشوي بصلصة الليمون والثوم." },
    { category: 'lunch', name_en: "Chicken Mandi", name_ar: "مندي دجاج", desc_en: "Classic Yemeni smoky rice and chicken.", desc_ar: "مندي دجاج يمني تقليدي." },

    // DINNER (50)
    { category: 'dinner', name_en: "Lentil Soup", name_ar: "شوربة العدس", desc_en: "Classic yellow lentil soup with lemon.", desc_ar: "شوربة عدس أصفر كلاسيكية بالليمون." },
    { category: 'dinner', name_en: "Fattoush Salad", name_ar: "سلطة فتوش", desc_en: "Garden salad with crispy bread and sumac.", desc_ar: "سلطة خضراء بالخبز المقرمش والسماق." },
    { category: 'dinner', name_en: "Taboooula", name_ar: "تبولة", desc_en: "Parsley, tomato, and bulgur salad.", desc_ar: "سلطة بقدونس وطماطم وبرغل." },
    { category: 'dinner', name_en: "Mutabbal", name_ar: "متبل باذنجان", desc_en: "Roasted eggplant dip with tahini.", desc_ar: "تغميسة باذنجان مشوي مع الطحينة." },
    { category: 'dinner', name_en: "Pumpkin Soup", name_ar: "شوربة قرع", desc_en: "Creamy roasted pumpkin soup.", desc_ar: "شوربة قرع كريمية مشوية." },
    { category: 'dinner', name_en: "Greek Salad", name_ar: "سلطة يونانية", desc_en: "Feta, olives, and cucumbers in olive oil.", desc_ar: "فيتا وزيتون وخيار بزيت الزيتون." },
    { category: 'dinner', name_en: "Chicken Corn Soup", name_ar: "شوربة ذرة بدجاج", desc_en: "Hearty soup with sweet corn and chicken.", desc_ar: "شوربة مشبعة بالذرة والدجاج." },
    { category: 'dinner', name_en: "Vegetable Crudités", name_ar: "خضروات مع حمص", desc_en: "Fresh veggies with hummus dip.", desc_ar: "خضروات طازجة مع تغميسة حمص." },
    { category: 'dinner', name_en: "Mushroom Soup", name_ar: "شوربة فطر", desc_en: "Rich and earthy cream of mushroom.", desc_ar: "شوربة فطر كريمية غنية." },
    { category: 'dinner', name_en: "Caesar Salad", name_ar: "سلطة سيزر", desc_en: "Romaine lettuce with croutons and dressing.", desc_ar: "خس مع خبز محمص وصلصة سيزر." },
    { category: 'dinner', name_en: "Chicken Caesar Wrap", name_ar: "لفافة سيزر", desc_en: "Classic salad in a light wrap.", desc_ar: "سلطة سيزر في لفافة خفيفة." },
    { category: 'dinner', name_en: "Tomato Basil Soup", name_ar: "شوربة طماطم بالريحان", desc_en: "Smooth tomato soup with fresh basil.", desc_ar: "شوربة طماطم ناعمة بالريحان الطازج." },
    { category: 'dinner', name_en: "Kibbeh Scouring", name_ar: "كبة مقلية", desc_en: "Bulgur shells with meat and pine nuts.", desc_ar: "أقراص كبة باللحم والصنوبر." },
    { category: 'dinner', name_en: "Halloumi Salad", name_ar: "سلطة حلوم", desc_en: "Grilled halloumi over mixed greens.", desc_ar: "حلوم مشوي فوق سلطة خضراء خضراء." },
    { category: 'dinner', name_en: "Minestrone Soup", name_ar: "شوربة مينستروني", desc_en: "Italian veggie soup with pasta pieces.", desc_ar: "شوربة خضار إيطالية مع المكرونة." },
    { category: 'dinner', name_en: "Spring Rolls", name_ar: "سبرينغ رولز", desc_en: "Crispy rolls with veggie filling.", desc_ar: "لفائف مقرمشة محشوة بالخضار." },
    { category: 'dinner', name_en: "Quinoa Salad", name_ar: "سلطة كينوا", desc_en: "Nutritious quinoa with peppers and herbs.", desc_ar: "كينوا مغذية مع الفلفل والأعشاب." },
    { category: 'dinner', name_en: "Beef Consommé", name_ar: "مرق لحم صافي", desc_en: "Clear beef broth with light spices.", desc_ar: "مرق لحم صافي مع بهارات خفيفة." },
    { category: 'dinner', name_en: "Shrimp Cocktail", name_ar: "كوكتيل ربيان", desc_en: "Boiled shrimp with tangy rose sauce.", desc_ar: "ربيان مسلوق بصلصة وردية منعشة." },
    { category: 'dinner', name_en: "Garlic Bread", name_ar: "خبز بالثوم", desc_en: "Toasted slices with garlic and herbs.", desc_ar: "خبز محمص بالثوم والأعشاب." },
    { category: 'dinner', name_en: "Roasted Veggie Salad", name_ar: "سلطة خضار مشوية", desc_en: "Mix of peppers, eggplant, and zucchini.", desc_ar: "مزيج فلفل وباذنجان وكوسا مشوية." },
    { category: 'dinner', name_en: "French Onion Soup", name_ar: "شوربة بصل فرنسية", desc_en: "Rich onion broth with melted cheese toast.", desc_ar: "مرق بصل غني ببرش البرشوتو." },
    { category: 'dinner', name_en: "Hummus with Beef", name_ar: "حمص باللحمة", desc_en: "Creamy hummus topped with spicy beef bits.", desc_ar: "حمص كريمي مغطى بقطع لحم متبلة." },
    { category: 'dinner', name_en: "Beetroot Salad", name_ar: "سلطة شمندر", desc_en: "Red beets with feta and balsamic.", desc_ar: "شمندر أحمر مع فيتا وبلسميك." },
    { category: 'dinner', name_en: "Clear Veggie Soup", name_ar: "شوربة خضار صافية", desc_en: "Nutritious mix of daily fresh veggies.", desc_ar: "مزيج مغذي من خضروات اليوم." },
    { category: 'dinner', name_en: "Samosas", name_ar: "سمبوسة", desc_en: "Fried pastries with potato or meat.", desc_ar: "معجنات مقلية بالبطاطس أو اللحم." },
    { category: 'dinner', name_en: "Chickpea Salad", name_ar: "سلطة حمص", desc_en: "Boiled chickpeas with cumin and lemon.", desc_ar: "حمص مسلوق بالكمون والليمون." },
    { category: 'dinner', name_en: "Tuna Niçoise", name_ar: "سلطة نيسواز", desc_en: "Tuna, eggs, and beans over greens.", desc_ar: "تونة وبيض وفاصوليا في سلطة نيسواز." },
    { category: 'dinner', name_en: "Potato Leek Soup", name_ar: "شوربة بطاطس وكراث", desc_en: "Very creamy and filling winter soup.", desc_ar: "شوربة بطاطس وكراث كريمية ومشبعة." },
    { category: 'dinner', name_en: "Mini Pizza Bites", name_ar: "بيتزا صغيرة", desc_en: "Bite-sized pizzas with olives and corn.", desc_ar: "قطع بيتزا صغيرة بالزيتون والذرة." },
    { category: 'dinner', name_en: "Coleslaw", name_ar: "كول سلو", desc_en: "Cabbage and carrot in creamy dressing.", desc_ar: "كرنب وجزر بصلصة كريمية." },
    { category: 'dinner', name_en: "Broccoli Soup", name_ar: "شوربة بروكلي", desc_en: "Warm broccoli soup with a hint of cream.", desc_ar: "شوربة بروكلي دافئة بالقشدة." },
    { category: 'dinner', name_en: "Eggplant Dip (Baba Ganoush)", name_ar: "بابا غنوج", desc_en: "Smoky eggplant with peppers and walnuts.", desc_ar: "باذنجان مدخن بالفلفل والجوز." },
    { category: 'dinner', name_en: "Fruit Nut Salad", name_ar: "سلطة فواكه وجوز", desc_en: "Mix of berries and premium pecans.", desc_ar: "مزيج توت وجوز بكان فاخر." },
    { category: 'dinner', name_en: "Spinach Soup", name_ar: "شوربة سبانخ", desc_en: "Fresh green spinach with potato base.", desc_ar: "شوربة سبانخ خضراء بقاعدة بطاطس." },
    { category: 'dinner', name_en: "Cheese Platter", name_ar: "طبق أجبان", desc_en: "Assorted cheeses with crackers and grapes.", desc_ar: "تشكيلة أجبان مع رقائق وعنب." },
    { category: 'dinner', name_en: "Beef Carpaccio", name_ar: "كرباتشو لحم", desc_en: "Thin slices of raw beef with rockets.", desc_ar: "شرائح لحم رقيقة جداً مع الجرجير." },
    { category: 'dinner', name_en: "Miso Soup", name_ar: "شوربة ميسو", desc_en: "Japanese style light broth with tofu.", desc_ar: "شوربة يابانية خفيفة مع التوفو." },
    { category: 'dinner', name_en: "Garlic Prawns", name_ar: "ربيان بالثوم", desc_en: "Sauteed prawns in a garlicky butter.", desc_ar: "ربيان مقلي في زبدة الثوم." },
    { category: 'dinner', name_en: "Waldorf Salad", name_ar: "سلطة والدورف", desc_en: "Apples, grapes, and walnuts with mayo.", desc_ar: "تفاح وعنب وجوز بالمايونيز." },
    { category: 'dinner', name_en: "Stuffed Mushrooms", name_ar: "مشروم محشي", desc_en: "Baked mushrooms with herb stuffing.", desc_ar: "مشروم مخبوز بحشوة الأعشاب." },
    { category: 'dinner', name_en: "Thai Green Salad", name_ar: "سلطة تايلاندية", desc_en: "Spicy papaya and nut salad.", desc_ar: "سلطة بابايا ومكسرات حارة." },
    { category: 'dinner', name_en: "Butternut Squash Soup", name_ar: "شوربة يقطين", desc_en: "Sweet and creamy yellow soup.", desc_ar: "شوربة يقطين حلوة وكريمية." },
    { category: 'dinner', name_en: "Caprese Sticks", name_ar: "أعواد كابريزي", desc_en: "Mozzarella and cherry tomatoes on skewers.", desc_ar: "موزاريلا وطماطم كرزية في أعواد." },
    { category: 'dinner', name_en: "Cold Pasta Salad", name_ar: "سلطة مكرونة باردة", desc_en: "Pasta with veggies and Italian dressing.", desc_ar: "مكرونة بالخضار والصلصة الإيطالية." },
    { category: 'dinner', name_en: "Asparagus Soup", name_ar: "شوربة هليون", desc_en: "Light and elegant green soup.", desc_ar: "شوربة هليون خضراء خفيفة." },
    { category: 'dinner', name_en: "Oysters", name_ar: "محار", desc_en: "Fresh oysters served on ice with lemon.", desc_ar: "محار طازج على الثلج مع ليمون." },
    { category: 'dinner', name_en: "Antipasto Plate", name_ar: "طبق مقبلات إيطالي", desc_en: "Mix of meats, cheeses, and olives.", desc_ar: "مزيج لحوم وأجبان وزيتون." },
    { category: 'dinner', name_en: "Beef Carpaccio Wrap", name_ar: "لفافة كرباتشو اللحم", desc_en: "Thin beef slices in a whole grain wrap.", desc_ar: "شرائح لحم رقيقة في لفافة الحبوب." },
    { category: 'dinner', name_en: "Lentil & Kale Soup", name_ar: "شوربة عدس وكيل", desc_en: "Healthy update to classic lentil soup.", desc_ar: "تحديث صحي لشوربة العدس الكلاسيكية." },

    // DESSERT (50)
    { category: 'dessert', name_en: "Cheese Kunafa", name_ar: "كنافة بالجبن", desc_en: "Classic Nabulsi kunafa with rose syrup.", desc_ar: "كنافة نابلسية بالجبن والقطر." },
    { category: 'dessert', name_en: "Pistachio Baklava", name_ar: "بقلاوة بالفستق", desc_en: "Flaky layers with premium pistachios.", desc_ar: "طبقات هشة محشوة بالفستق الفاخر." },
    { category: 'dessert', name_en: "Um Ali", name_ar: "أم علي", desc_en: "Egypian bread pudding with nuts and milk.", desc_ar: "بودينج الخبز المصري بالمكسرات والحليب." },
    { category: 'dessert', name_en: "Qatayef with Walnuts", name_ar: "قطايف بالجوز", desc_en: "Stuffed pancakes served with syrup.", desc_ar: "فطائر قطايف محشوة بالجوز والقطر." },
    { category: 'dessert', name_en: "Rice Pudding (Riz bi Haleeb)", name_ar: "أرز بحليب", desc_en: "Aromatic pudding with orange blossom water.", desc_ar: "بودينج أرز بماء زهر البرتقال." },
    { category: 'dessert', name_en: "Luqaimat", name_ar: "لقيمات", desc_en: "Golden crunchy balls with date syrup.", desc_ar: "كرات ذهبية مقرمشة بدبس التمر." },
    { category: 'dessert', name_en: "Ashta with Honey", name_ar: "قشطة بالعسل", desc_en: "Clotted cream topped with honey and nuts.", desc_ar: "قشطة بلدي بالعسل والمكسرات." },
    { category: 'dessert', name_en: "Date Ma'amoul", name_ar: "معمول تمر", desc_en: "Middle Eastern shortbread filled with dates.", desc_ar: "بسكويت هش محشو بعجينة التمر." },
    { category: 'dessert', name_en: "Muhallabieh", name_ar: "مهلبية", desc_en: "Milk custard with rose water and pistachios.", desc_ar: "كسترد الحليب بماء الورد والفستق." },
    { category: 'dessert', name_en: "Zalabia", name_ar: "زلابية", desc_en: "Fried dough rings dusted with sugar.", desc_ar: "حلقات عجين مقلية مرشوشة بالسكر." },
    { category: 'dessert', name_en: "Basbousa", name_ar: "بسبوسة", desc_en: "Semolina cake soaked in aromatic syrup.", desc_ar: "هريسة سميد مسقية بالقطر العطري." },
    { category: 'dessert', name_en: "Balah El Sham", name_ar: "بلح الشام", desc_en: "Syrian style churros in cold syrup.", desc_ar: "أصابع عجين مقلية بالقطر البارد." },
    { category: 'dessert', name_en: "Chocolate Date Balls", name_ar: "كرات تمر بالشوكولاتة", desc_en: "Healthy truffles with dates and cocoa.", desc_ar: "كرات تمر صحية مع الكاكاو." },
    { category: 'dessert', name_en: "Turkish Delight", name_ar: "راحة حلقوم", desc_en: "Gel-based sweets with nuts and starch.", desc_ar: "حلوى الحلقوم محشوة بالمكسرات." },
    { category: 'dessert', name_en: "Rice with Saffron (Sholeh Zard)", name_ar: "شعلة زرد", desc_en: "Persian saffron rice pudding.", desc_ar: "بودينج أرز بالزعفران على الطريقة الفارسية." },
    { category: 'dessert', name_en: "Semolina Halva", name_ar: "حلاوة سميد", desc_en: "Dense semolina sweet with toasted nuts.", desc_ar: "حلوى سميد كثيفة بالمكسرات المحمصة." },
    { category: 'dessert', name_en: "Fruit Skewers", name_ar: "أسياخ فواكه", desc_en: "Mix of seasonal fruits with mint syrup.", desc_ar: "مزيج فواكه موسمية بقطر النعناع." },
    { category: 'dessert', name_en: "Carrot Halwa", name_ar: "حلاوة جزر", desc_en: "Indian sweet carrot pudding with milk.", desc_ar: "بودينج جزر حلو بالحليب." },
    { category: 'dessert', name_en: "Arabic Ice Cream", name_ar: "بوظة عربية", desc_en: "Mastic flavored ice cream with pistachios.", desc_ar: "بوظة بنكهة المستكة والفستق الحلبي." },
    { category: 'dessert', name_en: "Apricot Sheet (Qamar al-Din)", name_ar: "قمر الدين", desc_en: "Sun-dried apricot leather dessert.", desc_ar: "حلوى جلد المشمش المجفف." },
    { category: 'dessert', name_en: "Kunafa Rolls", name_ar: "أصابع كنافة", desc_en: "Cylindrical kunafa rolls with walnuts.", desc_ar: "أصابع كنافة ملفوفة بالجوز." },
    { category: 'dessert', name_en: "Date Cake", name_ar: "كيكة التمر", desc_en: "Moist sponge cake with dates and caramel.", desc_ar: "كيكة هشة بالتمر والكراميل." },
    { category: 'dessert', name_en: "Sutlac", name_ar: "سوتلاش", desc_en: "Turkish baked rice pudding.", desc_ar: "بودينج أرز تركي مخبوز بالفرن." },
    { category: 'dessert', name_en: "Baklava Cheesecake", name_ar: "تشيز كيك بقلاوة", desc_en: "Fusion dessert with phyllo and cream cheese.", desc_ar: "حلوى مبتكرة بين البقلاوة والتشيز كيك." },
    { category: 'dessert', name_en: "Honey Fried Bananas", name_ar: "موز مقلي بالعسل", desc_en: "Caramelized bananas with a honey glaze.", desc_ar: "موز مكرمل مغطى بالعسل." },
    { category: 'dessert', name_en: "Layali Lubnan", name_ar: "ليالي لبنان", desc_en: "Semolina pudding with rose water and ashta.", desc_ar: "بودينج سميد بماء الورد والقشطة." },
    { category: 'dessert', name_en: "Walnut Ma'amoul", name_ar: "معمول جوز", desc_en: "Buttery pastry with spiced walnut filling.", desc_ar: "معمول هش محشو بالجوز المتبل." },
    { category: 'dessert', name_en: "Ekmek Kadayifi", name_ar: "خبز كنافة", desc_en: "Bread pudding with thick clotted cream.", desc_ar: "بودينج خبز مع القشطة الكثيفة." },
    { category: 'dessert', name_en: "Teffaya Date Balls", name_ar: "كرات تمر بالمكسرات", desc_en: "Small bites with coconut and dates.", desc_ar: "لقيمات تمر صغيرة بجوز الهند." },
    { category: 'dessert', name_en: "Carob Molasses Halva", name_ar: "حلاوة دبس خروب", desc_en: "Dark healthy dessert with tahini.", desc_ar: "حلوى داكنة صحية بدبس الخروب والطحينة." },
    { category: 'dessert', name_en: "Hibiscus Pear", name_ar: "كمثرى بالكركديه", desc_en: "Pears poached in bright red hibiscus tea.", desc_ar: "كمثرى مسلوقة في شاي الكركديه." },
    { category: 'dessert', name_en: "Sesame Bar (Simsimiyya)", name_ar: "سمسمية", desc_en: "Crunchy honey sesame slabs.", desc_ar: "شرائح سمسم بالعسل مقرمشة." },
    { category: 'dessert', name_en: "Pumpkin Halwa", name_ar: "حلاوة قرع", desc_en: "Soft spiced pumpkin sweet with nuts.", desc_ar: "حلوى قرع ناعمة متبلة بالمكسرات." },
    { category: 'dessert', name_en: "Rose Jelly", name_ar: "جيلي الورد", desc_en: "Soft jelly infused with rose petal water.", desc_ar: "جيلي ناعم منقوع بماء بتلات الورد." },
    { category: 'dessert', name_en: "Date & Almond Tart", name_ar: "تارت التمر واللوز", desc_en: "Shortcrust pastry with date paste.", desc_ar: "تارت هشة بعجينة التمر." },
    { category: 'dessert', name_en: "Ghorayeba", name_ar: "غريبة", desc_en: "Meltingly soft butter cookies with pistachios.", desc_ar: "بسكويت الزبدة الناعم بالفستق." },
    { category: 'dessert', name_en: "Ashta Filo Parcels", name_ar: "زنود الست", desc_en: "Filo pastry rolls filled with cream.", desc_ar: "لفائف فيلو محشوة بالقشطة." },
    { category: 'dessert', name_en: "Fig & Walnut Cake", name_ar: "كيكة تين وجوز", desc_en: "Rustic cake with dried figs and walnuts.", desc_ar: "كيكة ريفية بالتين المجفف والجوز." },
    { category: 'dessert', name_en: "Coconut Semolina Cake", name_ar: "هريسة جوز هند", desc_en: "Sweet semolina cake with coconut flakes.", desc_ar: "هريسة سميد حلوة ببرش جوز الهند." },
    { category: 'dessert', name_en: "Saffron Bundt Cake", name_ar: "كيكة زعفران", desc_en: "Fragrant yellow cake with saffron glaze.", desc_ar: "كيكة صفراء عطرية بصوص الزعفران." },
    { category: 'dessert', name_en: "Mshabak", name_ar: "مشبك", desc_en: "Fried web-like dough soaked in syrup.", desc_ar: "عجين مقلي بشكل شبكي مشبع بالقطر." },
    { category: 'dessert', name_en: "Date Cheesecake", name_ar: "تشيز كيك التمر", desc_en: "Creamy cheesecake on a date base.", desc_ar: "تشيز كيك كريمي بقاعدة التمر." },
    { category: 'dessert', name_en: "Pistachio Pudding", name_ar: "بودينج فستق", desc_en: "Rich green custard with crushed pistachios.", desc_ar: "كسترد أخضر غني بالفستق المجروش." },
    { category: 'dessert', name_en: "Stuffed Dates", name_ar: "تمر محشي", desc_en: "Premium dates stuffed with walnuts and cream.", desc_ar: "تمر فاخر محشو بالجوز والقشطة." },
    { category: 'dessert', name_en: "Asafiri Qatayef", name_ar: "قطايف عصافيري", desc_en: "Small open pancakes filled with ashta.", desc_ar: "قطايف صغيرة مفتوحة محشوة بالقشطة." },
    { category: 'dessert', name_en: "Mango Mousse", name_ar: "موس مانجو", desc_en: "Light and airy fresh mango dessert.", desc_ar: "حلوى موس المانجو الطازجة والخفيفة." },
    { category: 'dessert', name_en: "Pistachio Cookies", name_ar: "كوكيز فستق", desc_en: "Soft cookies with premium ground pistachios.", desc_ar: "بسكويت ناعم بالفستق الحلبي المطحون." },
    { category: 'dessert', name_en: "Date Truffles", name_ar: "ترافلز التمر", desc_en: "Exquisite date balls rolled in cocoa powder.", desc_ar: "كرات تمر فاخرة مغطاة ببودرة الكاكاو." },
    { category: 'dessert', name_en: "Rice Flour Halva", name_ar: "حلاوة دقيق الأرز", desc_en: "Traditional white halva with rose water.", desc_ar: "حلاوة بيضاء تقليدية بماء الورد." },
    { category: 'dessert', name_en: "Orange Honey Sorbet", name_ar: "سوربيه برتقال وعسل", desc_en: "Icy refreshing citrus dessert.", desc_ar: "حلوى مثلجة منعشة بنكهة البرتقال." },
];
